name: Deploy First to vps

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/administrator/vpdeploy
            git pull
            docker-compose up -d --build
